### ISSUE TITLE
organisaties met niet bestaande uri

### ISSUE THREAD

**Issue by pvgenuchten** [dataoverheid/dcat-ap-donl-waardelijsten#2]
het is niet helemaal duidelijk waar de organisatie uri's beheerd worden, daarom heb ik dit issue elders aangemaakt, echter die repository lijkt niet meer courant. Daarom vanuit hier een referentie 
https://github.com/dataoverheid/waardelijsten/issues/1

**Comment by WterBerg** [comment]
De waardelijsten worden _beheerd_ op data.overheid.nl zelf en worden mbv scripts in deze repository (https://github.com/dataoverheid/dcat-ap-donl-waardelijsten/blob/master/src/waardelijsten_updater.py) omgezet naar de daadwerkelijke waardelijsten die _gepubliceerd_ worden op [waardelijsten.dcat-ap-donl.nl/](https://waardelijsten.dcat-ap-donl.nl/).

De dataoverheid/waardelijsten repository is inderdaad niet meer actueel.

---

Ik zie inderdaad dat de webserver de organisatie/{organisatie naam} URL's niet goed redirect.

Huidig:
http://data.overheid.nl/organisatie/prorail > https://data.overheid.nl/community/organisaties/prorail

Correcte URL:
http://data.overheid.nl/organisatie/prorail > https://data.overheid.nl/community/organization/prorail

Dit zal ik intern aankaarten. Bedankt voor de melding!

**Comment by pvgenuchten** [comment]
Gekoppeld issue https://github.com/dataoverheid/waardelijsten/issues/1 is gesloten, probleem is opgelost.
